language: node_js

jobs:
  include:
    - stage: test
      node_js: '12'
      install:
        - npm install
      script:
        - npm run lint
        - npm run test
    - stage: npm release
      if: tag IS present
      node_js: '12'
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
