title: '[General]: '
labels: ['discussion']
body:
  - type: textarea
    attributes:
      label: Summary
      description: What do you want to start a conversation about?
    validations:
      required: true

  - type: checkboxes
    id: relations
    attributes:
      label: If applicable, which variants of Embla Carousel are relevant to this conversation?
      description: Check all that apply.
      options:
        - label: embla-carousel **(Core)**
        - label: embla-carousel-react
        - label: embla-carousel-vue
        - label: embla-carousel-svelte
        - label: embla-carousel-autoplay
        - label: embla-carousel-solid
        - label: embla-carousel-auto-height
        - label: embla-carousel-class-names
        - label: embla-carousel-docs **(Documentation)**
        - label: embla-carousel-docs **(Generator)**

  - type: textarea
    attributes:
      label: Additional information
      description: Any code snippets, error messages, or dependency details that may be related?
      render: js
    validations:
      required: false

  - type: input
    attributes:
      label: CodeSandbox example
      description: A link to a minimal reproduction is helpful for collaborative debugging!
    validations:
      required: false
