title: '[Feat]: '
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request!**
        We kindly ask that you search to see if an issue [already exists](https://github.com/davidjerleke/embla-carousel/issues?q=is%3Aissue+sort%3Acreated-desc+) for your feature.

        We are happy to accept contributions from our users. For more details see [here](https://github.com/davidjerleke/embla-carousel/blob/master/CONTRIBUTING.md#new-features).

  - type: checkboxes
    id: relations
    attributes:
      label: Which variants of Embla Carousel are relevant to this feature request?
      description: Check all that apply.
      options:
        - label: embla-carousel **(Core)**
        - label: embla-carousel-react
        - label: embla-carousel-vue
        - label: embla-carousel-svelte
        - label: embla-carousel-autoplay
        - label: embla-carousel-solid
        - label: embla-carousel-auto-height
        - label: embla-carousel-class-names
        - label: embla-carousel-docs **(Documentation)**
        - label: embla-carousel-docs **(Generator)**

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request
      placeholder: 'I think this feature would be great because...'
      value: 'Describe your feature request...'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature here.
      placeholder: ex. screenshots, stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
      value: 'Additional details here...'
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/CONTRIBUTING.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues
          required: true
        - label: I agree to follow this project's Contributing Guidelines for feature requests
          required: true
