name: Continuous Deployment

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup node for npmjs.org as registry
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install 🔧
        run: yarn install

      - name: Build 🏗️
        run: yarn build

      - name: NPM PKG Publish 🎉
        run: yarn workspaces foreach --topological-dev --exclude '{embla-carousel-monorepo,embla-carousel-docs}' npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
